// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-759j57GxPgq-sMqjMWLebJKlBBjePfk',
    appId: '1:107222566849:web:88f932c10378c0640e9140',
    messagingSenderId: '107222566849',
    projectId: 'mad-cw2-ku',
    authDomain: 'mad-cw2-ku.firebaseapp.com',
    storageBucket: 'mad-cw2-ku.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyyEW8zOrhi_20nxMCj6HBmEzk400hPmo',
    appId: '1:107222566849:android:d6bd8fa33a5b998e0e9140',
    messagingSenderId: '107222566849',
    projectId: 'mad-cw2-ku',
    storageBucket: 'mad-cw2-ku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUi-PCkJ6EYHUOSwiENLkvCix8t5OfRC4',
    appId: '1:107222566849:ios:458e93966435bb3f0e9140',
    messagingSenderId: '107222566849',
    projectId: 'mad-cw2-ku',
    storageBucket: 'mad-cw2-ku.firebasestorage.app',
    androidClientId: '107222566849-2ki35v1isu43flnn4h0pdn8sgdl0iv1p.apps.googleusercontent.com',
    iosClientId: '107222566849-vam938lkr9i4vigu1ptcnb37ak0v2ufo.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUi-PCkJ6EYHUOSwiENLkvCix8t5OfRC4',
    appId: '1:107222566849:ios:458e93966435bb3f0e9140',
    messagingSenderId: '107222566849',
    projectId: 'mad-cw2-ku',
    storageBucket: 'mad-cw2-ku.firebasestorage.app',
    androidClientId: '107222566849-2ki35v1isu43flnn4h0pdn8sgdl0iv1p.apps.googleusercontent.com',
    iosClientId: '107222566849-vam938lkr9i4vigu1ptcnb37ak0v2ufo.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-759j57GxPgq-sMqjMWLebJKlBBjePfk',
    appId: '1:107222566849:web:fbc07af8f4852be80e9140',
    messagingSenderId: '107222566849',
    projectId: 'mad-cw2-ku',
    authDomain: 'mad-cw2-ku.firebaseapp.com',
    storageBucket: 'mad-cw2-ku.firebasestorage.app',
  );

}